### PR TITLE
[Resolve #116] Fix an error message for unsupported Supfile version

### LINKED ISSUE #116: Sup would not be updated
If I run `sup`, the console shows this message:

```
unsupported version 1.0

Please update sup by `go get -u github.com/pressly/sup/cmd/sup`
```

But, that command does not update the sup.

Any solutions?

### PR DESCRIPTION
**Pull request by mingrammer**
I fixed an error message for unsupported Supfile version for avoiding confused experience

### CODE REVIEW

File: supfile.go [hunk 1]
```diff
@@ -213,7 +221,7 @@ func NewSupfile(file string) (*Supfile, error) {
 	case "0.4", "0.5":
 
 	default:
-		return nil, ErrMustUpdate{"unsupported version " + conf.Version}
+		return nil, ErrUnsupportedVersion{"unsupported version " + conf.Version}
```
Comment (VojtechVitek) [inline supfile.go]: `unsupported Supfile version` ?

File: supfile.go [hunk 2]
```diff
@@ -146,10 +146,18 @@ type ErrMustUpdate struct {
...
+type ErrUnsupportedVersion struct {
+	Msg string
+}
+
 func (e ErrMustUpdate) Error() string {
 	return fmt.Sprintf("%v\n\nPlease update sup by `go get -u github.com/pressly/sup/cmd/sup`", e.Msg)
 }
 
+func (e ErrUnsupportedVersion) Error() string {
+	return fmt.Sprintf("%v\n\nCheck your Supfile version (available versions: 0.{1|2|3|4|5})", e.Msg)
```
Comment (VojtechVitek) [inline supfile.go]: can we list the latest version only, ie. v0.5?

**Comment by mingrammer** [comment]
Reflected your suggestions!
