### PR TITLE
Env vars should be ordered

### LINKED ISSUE #10: Random ENV failures when vars depend on each other
Since YAML parses ENV vars into a map, we loose the declaration order, and thus the following randomly fails:

```yaml
env:
  WORKDIR: /var/www/
  CONFDIR: $WORKDIR/config # this becomes /var/www/config OR /config randomly
```

### PR DESCRIPTION
**Pull request by stengaard**
Since maps in go are by definition in random order environment variables
could not rely on a previously defined value to be present. This
addresses that problem by introducing an ordered map type.

This fixes #10

### CODE REVIEW

File: supfile.go [hunk 1]
```diff
@@ -13,21 +13,66 @@ import (
 	"gopkg.in/yaml.v2"
 )
 
+// EnvVar represents an environment variable
+type EnvVar struct {
+	Key   string
+	Value string
+}
```
Comment (VojtechVitek) [inline supfile.go]: This is great @stengaard!

How does this differ from https://godoc.org/gopkg.in/yaml.v2#MapItem and https://godoc.org/gopkg.in/yaml.v2#MapSlice ?

I really appreciate your effort. We might use something similar even for the other `map[string]Command` that we use, so we could even have multiple `upload`/`run`/`local` within a command/target with a well-defined order! :)

File: supfile.go [hunk 2]
```diff
@@ -13,21 +13,66 @@ import (
...
+// AsExport returns the environment variable as a bash export statement
+func (e EnvVar) AsExport() string {
+	return `export ` + e.Key + `="` + e.Value + `";`
+}
+
+// EnvList is a list of environment variables that maps to a YAML map,
+// but maintains order, enabling late variables to reference early variables.
+type EnvList []EnvVar
+
+func (e *EnvList) UnmarshalYAML(ufn func(interface{}) error) error {
```
Comment (VojtechVitek) [inline supfile.go]: Can you call `ufn` `unmarshal` instead (as in yaml pkg)?

File: supfile.go [hunk 3]
```diff
@@ -13,21 +13,66 @@ import (
...
+	d := []yaml.MapItem{}
+
+	err := ufn(&d)
+	if err != nil {
+		return err
+	}
+
+	*e = make(EnvList, 0, len(d))
```
Comment (VojtechVitek) [inline supfile.go]: I'd prefer not setting the capacity, so we could `.Set()` even later in the code.

File: supfile.go [hunk 4]
```diff
@@ -13,21 +13,66 @@ import (
...
+func (e EnvVar) AsExport() string {
+	return `export ` + e.Key + `="` + e.Value + `";`
+}
+
+// EnvList is a list of environment variables that maps to a YAML map,
+// but maintains order, enabling late variables to reference early variables.
+type EnvList []EnvVar
+
+func (e *EnvList) UnmarshalYAML(ufn func(interface{}) error) error {
+	d := []yaml.MapItem{}
```
Comment (VojtechVitek) [inline supfile.go]: call it `items`

File: supfile.go (hunk 3 above)
Comment (VojtechVitek) [inline supfile.go]: In other words, it's not wrong... but `append()` would be faster later on (without re-allocation).

File: supfile.go (hunk 1 above)
Comment (stengaard) [inline supfile.go]: Mostly it's about hiding the `interface{}` which would be annoying to work with later on. Rather do a bit of work upfront and then having an actual sane type to work with.

File: supfile.go [hunk 5]
```diff
@@ -13,21 +13,66 @@ import (
...
+		e.Set(fmt.Sprintf("%v", v.Key), fmt.Sprintf("%v", v.Value))
+	}
+
+	return nil
+}
+
+// Set key to be equal value in this list.
+func (e *EnvList) Set(key, value string) {
+	// if key exists result will be redefinition
+	*e = append(*e, EnvVar{
```
Comment (VojtechVitek) [inline supfile.go]: You're appending here, thus relying on rewriting the var by `export a=b; export a=c;` order, right? Can we search and override the old value instead properly?

**Comment by VojtechVitek** [comment]
Very good contribution!

LGTM other than some minor nits. Let me test & merge once you answer/address my comments. Thanks! :)

File: supfile.go (hunk 1 above)
Comment (stengaard) [inline supfile.go]: Are you looking for something like:

```yaml
commands:
    all:
        upload:
           src: files/
           dst: /bin
        run: /bin/prepare.sh
        upload: 
            src: file1
            dst: file2
       run: /bin/build.sh
```

File: supfile.go (hunk 2 above)
Comment (stengaard) [inline supfile.go]: Sure thing

File: supfile.go (hunk 3 above)
Comment (stengaard) [inline supfile.go]: Not sure I follow - we can still do `.Set()` (`EnvList` has pointer receiver type). This is just a hint at the size so far.

File: supfile.go (hunk 4 above)
Comment (stengaard) [inline supfile.go]: Done.

File: supfile.go (hunk 1 above)
Comment (VojtechVitek) [inline supfile.go]: Correct, this is in my mind for a long run. What do you think about it?

But it needs more thinking, as we want to implement `onerror` #42 and `if` conditionals #45 as well :)

File: supfile.go (hunk 5 above)
Comment (stengaard) [inline supfile.go]: Yeah - was just being lazy. ;) I'll get it sorted.

File: supfile.go (hunk 3 above)
Comment (VojtechVitek) [inline supfile.go]: `make(EnvList, len(d))` instead of `make(EnvList, 0, len(d))`

File: supfile.go (hunk 1 above)
Comment (stengaard) [inline supfile.go]: I think you can mostly achieve the same thing with composing `command`s in `target`s, right? I can definitely see the use for several `run`s, but don't see the need for several `upload`s.

`run` could be done like this and you could have several shell commands in a row: https://gist.github.com/stengaard/4cd2a88693df2a3b54d3

File: supfile.go (hunk 3 above)
Comment (stengaard) [inline supfile.go]: Hm, don't think that would work. It would create a list of `len(d)` with zero values for `EnvVar` (ie blank `.Key`/`.Value`). 

http://play.golang.org/p/npEaCZxmdE

Comment (VojtechVitek) [inline supfile.go]: This is how you initialize slice of a certain length but withouth known capacity: http://play.golang.org/p/-Ykcz4xqoF

**Comment by eduardonunesp** [comment]
Indeed :+1:

**Comment by VojtechVitek** [comment]
LGTM
